### ISSUE TITLE
New tag/version with PHP 7 support

### ISSUE THREAD

**Issue by jrenggli** [xperseguers/t3ext-routing#13]
Hi @xperseguers 

Could you please create a current version of this extension with PHP 7 support. I don't know if there are any issues regarding PHP 7 pending.

Otherwise it would be nice to pull the current master as version 0.4.0 ? ;-)

Best,
Jonas

**Comment by xperseguers** [comment]
Support for PHP7 has been checked with eecafccba6e8d1d94c2765fb202c057653c209c1. Will release soon.
