### ISSUE TITLE
CamelCase controller names are wrong converted

### ISSUE THREAD

**Issue by nicodh** [xperseguers/t3ext-routing#17]
If you configure a UpperCamelCase controller name like this:
  name: 'Routes for list of all userGroups'
  uriPattern: 'userGroups'
  defaults:
    '@vendor': 'FOO'
    '@package':    'Bar'
    '@plugin':     'myplugin'
    '@controller': 'UserGroup'
    '@action':     'list'

the controller name is converted to User**g**roup, due to the GeneralUtility::underscoredToUpperCamelCase conversion in RoutingController::getControllerParameters

I don't see why the underscoredToUpperCamelCase conversion is needed at all, since there shouldn't be underscores in class names in Extbase...?

**Comment by xperseguers** [comment]
IIRC, origin of this dates back from when we did not have namespaces
