### ISSUE TITLE
Pagetree routing

### ISSUE THREAD

**Issue by runepiper** [xperseguers/t3ext-routing#20]
Hi Xavier,

I couldn't figure out if the extension also creates routes for the page tree. If not, it would be an awesome enhancement. It then will be a good choice over RealURL.

Regards

**Comment by tantegerda1** [comment]
Hi @runepiper,

I don't think that's the scope of this extension. It does not really do the same thing as RealURL (e.g. it does not *encode* URLs*). [As it says in the Readme](https://github.com/xperseguers/t3ext-routing/blob/master/README.rst#request-routing-service), it's goal is to let you 

> route HTTP/REST requests to your own **[extbase] controller/actions**.

I might be wrong or understood you wrong, but I'd say this is not what the extension is for (and I'm curious to what Xavier is going to say about that).

Context: I'm a long-time intensive user of both this wonderful extension (thanks, Xavier!) and RealURL.

---
*well, mostly not. There is a ViewHelper, but it does not do magic.

**Comment by xperseguers** [comment]
Exactly. this is not the purpose of this extension to replace RealURL or alike.

**Comment by runepiper** [comment]
Allright, makes sense. It's sad, but still looks like an awesome extension. Thanks for your answers.
