### ISSUE TITLE
Route with {@controller}

### ISSUE THREAD

**Issue by MaxGTR** [xperseguers/t3ext-routing#3]
Function "GeneralUtility::underscoredToUpperCamelCase" is not used on "$controllerParameters['@controller']" in "RoutingController.php".

Line 189:
$pluginParameters['controller'] = $controllerParameters['@controller'];
=> $pluginParameters['controller'] = GeneralUtility::underscoredToUpperCamelCase($controllerParameters['@controller']);

Line 192:
$_POST['controller'] = $controllerParameters['@controller'];
=> $_POST['controller'] = GeneralUtility::underscoredToUpperCamelCase($controllerParameters['@controller']);

**Comment by xperseguers** [comment]
How to reproduce?

**Comment by MaxGTR** [comment]
With uriPattern: 'my-demo/{@controller}/{@action}' currently you have to write your controller name in the URL with first letter in capital.
