### ISSUE TITLE
Bug Dispatch Controller (PUT, DELETE)

### ISSUE THREAD

**Issue by MaxGTR** [xperseguers/t3ext-routing#9]
With HTTP PUT or DELETE method, dispatch to the controller doesn't work, in my case it is an action of the third controller define in "ext_localconf.php", from error the system is searching action in the first controller. Effectively it works with an action of the first controller define in "ext_localconf.php".
With POST method it works fine.
With a debug on "RoutingController.php" the line code "$bootstrap->run('', $configuration)" returns nothing.

**Comment by MaxGTR** [comment]
With PUT method the default controller name is used (first define in "ext_localconf.php") because the request controller is not set in Controller Parameters.

Line 195 in "RoutingController.php":
`switch ($httpMethod) {`
`case 'GET':`
`$pluginParameters['controller'] = GeneralUtility::underscoredToUpperCamelCase($controllerParameters['@controller']);`
`break;`
`case 'POST':`
`$_POST['controller'] = GeneralUtility::underscoredToUpperCamelCase($controllerParameters['@controller']);`
`break;`
`}`
Only GET and POST methods are treated.

A soultion:
`case 'POST':`
`case 'PUT':`
`$_POST['controller'] = GeneralUtility::underscoredToUpperCamelCase($controllerParameters['@controller']);`
`break;`

Or:
`default:`
`$_POST['controller'] = GeneralUtility::underscoredToUpperCamelCase($controllerParameters['@controller']);`

**Comment by xperseguers** [comment]
Maybe you could provide a pull request adding the lines

```
case 'PUT':
case 'PATCH':
case 'DELETE':
```

These are all the additional standard REST methods as described on http://www.restapitutorial.com/lessons/httpmethods.html
